Feature/authentication
laurentiu-m/ebs-internship pull request #10
Opened 2024-12-31 14:06 UTC by laurentiu-m

2025-01-02 11:38 UTC, SirReaDy requested changes

2025-01-02 11:38 UTC, SirReaDy commented on client/src/features/auth/pages/Login.tsx
> +  const [error, setError] = useState({ message: '', active: false });
We can use react-hook-form hooks for setting errors
https://legacy.react-hook-form.com/api/useform/seterror/

Instead of a state, you can have a function that will parse the errors from back and the form Errors for the exact field, if applicable.

2025-01-02 11:38 UTC, SirReaDy commented on client/src/features/auth/pages/Login.tsx
> +        console.error('Failed to login: ', err.response?.data.message);
Please remove console logs after testing

2025-01-02 11:38 UTC, SirReaDy commented on client/src/features/auth/pages/Register.tsx
> +import { api } from '../../../api/index';
Fix import to be absolute.

2025-01-02 11:38 UTC, SirReaDy commented on client/src/features/auth/pages/Login.tsx
> +import { api } from '../../../api';
Fix import to be absolute. ex: import { api } from 'src/api' or from 'api'
If needed, add alias in the vite.config.ts

2025-01-02 11:38 UTC, SirReaDy commented on client/src/features/auth/pages/Register.tsx
> +    firstName: z.string().nonempty('First name is required').min(2, 'First name must be at least 2 characters'),
Would be nice to have the error messages in user's selected language.

2025-01-02 11:38 UTC, SirReaDy commented on client/src/features/auth/pages/Register.tsx
> +  const [error, setError] = useState({ message: '', active: false });
Similar here, we can use setErrors from react-hook-form

2025-01-02 11:38 UTC, SirReaDy commented on client/src/features/auth/pages/Login.tsx
> +        <input {...register('email')} type="email" className="form__input" placeholder="Email" />
Let's create a generic Input component, because you have the same structure everytime  that will receive:
```
name - for the register
type - optional, text by default
disabled - optional
className="form__input"
```

And we can use as follows: 
```
 <FormInput type="text" name="firstName" placeholder="First Name" register={register} errors={errors} />
```

You can also send errors, and leverage screen readers by using   aria-invalid={!!errors[name]}
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid

2025-01-09 12:10 UTC, SirReaDy requested changes

2025-01-09 12:10 UTC, SirReaDy commented on client/src/App.tsx
> +const Login = React.lazy(() => import('./features/auth/pages/Login').then((module) => ({ default: module.Login })));
Let's not over optimize from the start if not needed.  At this moment its unnecessary overhead

2025-01-09 12:10 UTC, SirReaDy commented on client/src/App.tsx
> +                <ProtectedRoute requiredRole="admin">
Create an enum with the roles definition, and with the routes.

2025-01-09 12:10 UTC, SirReaDy commented on client/src/api/users.ts
> +import { User, UserLogin, UserRegister } from '../types/index';
Fix import.
No need to import the "index" file.

Maybe you can import directly from 'types'

2025-01-09 12:10 UTC, SirReaDy commented on client/src/components/Unauthorized.tsx
> +  const role = localStorage.getItem('userRole');
Define the userRole in a constant file like
```
export  const USER_ROLE = 'userRole'
```

2025-01-09 12:10 UTC, SirReaDy commented on client/src/components/Unauthorized.tsx
> +  let location = '/login';
Try to avoid using let.

The idea to have a dashboard-admin is bad practice when we think security.

We should only have /dashboard, and make all the role checks in the Router and components.

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/pages/Login.tsx
> +import { loginSubmit } from '../utils/authUtils';
Add Alias to vite.config to either import from components or src/components. Migrate to absolute paths imports

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/pages/Login.tsx
> +  email: z.string().nonempty('Please add your email').email('Invalid email'),
If you have multi-language, add translations to the errors as well, or have them translated on the back based on the user selected language (a header)

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/pages/Register.tsx
> +  const genderOptions = [
If you do not add translations, move outside the render both genderOptions and languageOptions to avoid them rerendering

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/utils/authUtils.ts
> +    if (response.role === 'user') {
Use the new enum for the Roles

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/utils/authUtils.ts
> +      navigate(`/dashboard-${response.role}`);
As mentioned previously, bad practice to have the user role in the URL. Need to rethink to handle /dashboard only

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/utils/authUtils.ts
> +    if (err instanceof AxiosError) {
Create a function as an util, like getErrors or hook useErrors, where you will dynamic for all fields willl set the errors dynamicaly.

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/utils/authUtils.ts
> +    localStorage.setItem('accessToken', response.token);
Add accessToken and userRole to a constant file

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/utils/authUtils.ts
> +    if (response.role === 'user') {
Destructure user and data from response,

2025-01-09 12:10 UTC, SirReaDy commented on client/src/features/auth/utils/authUtils.ts
> +        errData.fields.map((error: { field: keyof UserRegisterForm; message: string }) => {
You can use forEach since its faster and you dont need a new array

2025-01-09 12:10 UTC, SirReaDy commented on client/src/router/ProtectedRoute.tsx
> +  const token = localStorage.getItem('accessToken');
Use the new defined constants

2025-01-09 12:10 UTC, SirReaDy commented on client/src/router/ProtectedRoute.tsx
> +          errorMessage: 'Token is invalid or expired. Please log in again.',
We should handle the errors from the backend, but, not sure if you would want to show on the UI the error. Navigating user to login should suffice.

2025-01-09 12:10 UTC, SirReaDy commented on client/src/router/ProtectedRoute.tsx
> +  });
Double check if the useEffect needs dependencies to avoid rerenders.

2025-01-09 12:10 UTC, SirReaDy commented on server/src/routes/authRoutes.ts
> +    res.status(404).json({
A better approach is to send only the missing field error. As example:

```
  const missingFields = [
    { field: "email", value: email },
    { field: "name", value: name },
    { field: "password", value: password },
    { field: "gender", value: gender },
    { field: "confirmPassword", value: confirmPassword },
    { field: "username", value: username },
    { field: "phone", value: phone },
    { field: "language", value: language },
  ].filter(({ value }) => !value);

  if (missingFields.length > 0) {
    res.status(400).json({
      error: "form_invalid",
      fields: missingFields.map(({ field }) => ({
        field,
        message: `Please complete the ${field} field`,
      })),
    });
    return
  }
```

This way, only the missing fields will receive the error.

2025-01-13 12:48 UTC, GribinetDaniel requested changes

2025-01-13 12:48 UTC, GribinetDaniel commented on .vscode/cspell.json
> +{
add to gitignore

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/App.tsx
> +import { Register } from '@features/auth/pages/Register';
add an index.ts file in faetures/auth and export there Login and Register pages

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/App.tsx
> +import { NotFound } from '@components/NotFound';
The same thing with components

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/api/users.ts
> +export const getUsers = async (): Promise<User[]> => {
let's create users object where we will have all our api calls

`users = {
getList: async() => ....
}`

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/components/Loading.tsx
> +  return <span className="loader"></span>;
Use shorter version to write html tags if you don't have child.:
<span />

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/components/NotFound.tsx
> +      <Link to="/dashboard">
Don't use hardcoded values. Use Routes.Dashboard

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/features/auth/components/Errors.tsx
> +export const Errors: React.FC<ErrorProps> = ({ allErrors }) => {
Remove React.Fc

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/features/auth/components/LanguageSelector.tsx
> +  const changeLanguage = (lang: string) => {
onChangeLanguage

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/features/auth/components/Select.tsx
> +    <select {...register(name)} defaultValue="" className={`form__select ${error && 'form__select--error'}`}>
Use placeholder instead of empty deafult value

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/features/auth/index.scss
> +    @include mixins.flex(center, center, column);
Change

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/locales/en.json
> +  "Login": {
use lowercase

2025-01-13 12:48 UTC, GribinetDaniel commented on client/src/locales/en.json
> +      "email-empty": "Please add your email",
let's use underscore instead of '-'

2025-01-13 12:48 UTC, GribinetDaniel commented on client/tsconfig.app.json
> +      "@auth-utils/*": ["src/features/auth/utils/*"],
Remove this 2 absolute paths

2025-01-13 12:48 UTC, GribinetDaniel commented on server/src/routes/authRoutes.ts
> +  const checkPassword = password === confirmPassword;
There is no need for this check

2025-01-13 12:48 UTC, GribinetDaniel commented on server/src/scripts/updateUsersData.ts
> +    gender: faker.helpers.arrayElement(["male", "female", "prefer not to say"]),
`prefer_not_to_say`

2025-01-13 12:48 UTC, GribinetDaniel commented on server/src/scripts/updateUsersData.ts
> +    language: faker.helpers.arrayElement(["English", "Romana"]),
There is no need for language on server side

2025-01-14 09:40 UTC, GribinetDaniel requested changes

2025-01-14 09:40 UTC, GribinetDaniel commented on client/src/features/auth/pages/Login.tsx
> +import { LanguageSelector } from '../components';
Import all of them in one line 
import { Errors, FormInput, LanguageSelector } from '../components';

2025-01-14 09:40 UTC, GribinetDaniel commented on client/src/features/auth/pages/Register.tsx
> +import { LanguageSelector } from '../components';
Also here

2025-01-14 09:40 UTC, GribinetDaniel commented on client/src/styles/index.scss
> +.loader::after {
Put this one in .loader class

```
.loader {
 ....

    &::after {
      ....
    }
}
```

2025-01-14 10:59 UTC, merged